DROP DATABASE TIENDA;
CREATE DATABASE TIENDA;
USE TIENDA;


CREATE TABLE PRODUCTO(
       ID INT AUTO_INCREMENT NOT NULL ,
       NOMBRE VARCHAR(45) NOT NULL,
       IMAGEN VARCHAR(245),
       PRIMARY KEY(ID));

INSERT INTO PRODUCTO(ID,NOMBRE,IMAGEN)VALUES(NULL,'TELEVISOR','IMG.JPG');

-- ALTER TABLE PERSONA ADD CONSTRAINT FK_TIPOIDENTIFICACION FOREIGN KEY (TIPOID_ID) REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION);
